
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fnafbitsandpieces.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenFreddyHeadBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredGoldenBonnieHeadBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFreddyHeadBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxytorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredFoxyHeadBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredChicaHeadBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.UnwitheredBonnieHeadBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.SpringBonnieHeadBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.FredbearLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.FredBearShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.FredBearHeadBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFreddyHeadBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerFoxyHeadBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerChicaHeadBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieTorsoBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieShowtimeBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieShowtimeABlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieRightLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieRightArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieLeftLegBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieLeftArmBlock;
import net.mcreator.fnafbitsandpieces.block.DinerBonnieHeadBlock;
import net.mcreator.fnafbitsandpieces.FnafBitsAndPiecesMod;

public class FnafBitsAndPiecesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FnafBitsAndPiecesMod.MODID);
	public static final RegistryObject<Block> UNWITHERED_FOXY_HEAD = REGISTRY.register("unwithered_foxy_head", () -> new UnwitheredFoxyHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXYTORSO = REGISTRY.register("unwithered_foxytorso", () -> new UnwitheredFoxytorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_RIGHT_ARM = REGISTRY.register("unwithered_foxy_right_arm", () -> new UnwitheredFoxyRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_LEFT_ARM = REGISTRY.register("unwithered_foxy_left_arm", () -> new UnwitheredFoxyLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_RIGHT_LEG = REGISTRY.register("unwithered_foxy_right_leg", () -> new UnwitheredFoxyRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_LEFT_LEG = REGISTRY.register("unwithered_foxy_left_leg", () -> new UnwitheredFoxyLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_SHOWTIME = REGISTRY.register("unwithered_foxy_showtime", () -> new UnwitheredFoxyShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_HEAD = REGISTRY.register("unwithered_freddy_head", () -> new UnwitheredFreddyHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_TORSO = REGISTRY.register("unwithered_freddy_torso", () -> new UnwitheredFreddyTorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_RIGHT_ARM = REGISTRY.register("unwithered_freddy_right_arm", () -> new UnwitheredFreddyRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_LEFT_ARM = REGISTRY.register("unwithered_freddy_left_arm", () -> new UnwitheredFreddyLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_RIGHT_LEG = REGISTRY.register("unwithered_freddy_right_leg", () -> new UnwitheredFreddyRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_LEFT_LEG = REGISTRY.register("unwithered_freddy_left_leg", () -> new UnwitheredFreddyLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_SHOWTIME = REGISTRY.register("unwithered_freddy_showtime", () -> new UnwitheredFreddyShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_HEAD = REGISTRY.register("unwithered_bonnie_head", () -> new UnwitheredBonnieHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_TORSO = REGISTRY.register("unwithered_bonnie_torso", () -> new UnwitheredBonnieTorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_RIGHT_ARM = REGISTRY.register("unwithered_bonnie_right_arm", () -> new UnwitheredBonnieRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_LEFT_ARM = REGISTRY.register("unwithered_bonnie_left_arm", () -> new UnwitheredBonnieLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_RIGHT_LEG = REGISTRY.register("unwithered_bonnie_right_leg", () -> new UnwitheredBonnieRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_LEFT_LEG = REGISTRY.register("unwithered_bonnie_left_leg", () -> new UnwitheredBonnieLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_SHOWTIME = REGISTRY.register("unwithered_bonnie_showtime", () -> new UnwitheredBonnieShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_HEAD = REGISTRY.register("unwithered_chica_head", () -> new UnwitheredChicaHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_TORSO = REGISTRY.register("unwithered_chica_torso", () -> new UnwitheredChicaTorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_RIGHT_ARM = REGISTRY.register("unwithered_chica_right_arm", () -> new UnwitheredChicaRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_LEFT_ARM = REGISTRY.register("unwithered_chica_left_arm", () -> new UnwitheredChicaLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_RIGHT_LEG = REGISTRY.register("unwithered_chica_right_leg", () -> new UnwitheredChicaRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_LEFT_LEG = REGISTRY.register("unwithered_chica_left_leg", () -> new UnwitheredChicaLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_SHOWTIME = REGISTRY.register("unwithered_chica_showtime", () -> new UnwitheredChicaShowtimeBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_HEAD = REGISTRY.register("spring_bonnie_head", () -> new SpringBonnieHeadBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_TORSO = REGISTRY.register("spring_bonnie_torso", () -> new SpringBonnieTorsoBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_RIGHT_ARM = REGISTRY.register("spring_bonnie_right_arm", () -> new SpringBonnieRightArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_LEFT_ARM = REGISTRY.register("spring_bonnie_left_arm", () -> new SpringBonnieLeftArmBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_RIGHT_LEG = REGISTRY.register("spring_bonnie_right_leg", () -> new SpringBonnieRightLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_LEFT_LEG = REGISTRY.register("spring_bonnie_left_leg", () -> new SpringBonnieLeftLegBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_SHOWTIME = REGISTRY.register("spring_bonnie_showtime", () -> new SpringBonnieShowtimeBlock());
	public static final RegistryObject<Block> FRED_BEAR_HEAD = REGISTRY.register("fred_bear_head", () -> new FredBearHeadBlock());
	public static final RegistryObject<Block> FREDBEAR_TORSO = REGISTRY.register("fredbear_torso", () -> new FredbearTorsoBlock());
	public static final RegistryObject<Block> FREDBEAR_RIGHT_ARM = REGISTRY.register("fredbear_right_arm", () -> new FredbearRightArmBlock());
	public static final RegistryObject<Block> FREDBEAR_LEFT_ARM = REGISTRY.register("fredbear_left_arm", () -> new FredbearLeftArmBlock());
	public static final RegistryObject<Block> FREDBEAR_RIGHT_LEG = REGISTRY.register("fredbear_right_leg", () -> new FredbearRightLegBlock());
	public static final RegistryObject<Block> FREDBEAR_LEFT_LEG = REGISTRY.register("fredbear_left_leg", () -> new FredbearLeftLegBlock());
	public static final RegistryObject<Block> FREDBEAR_SHOWTIME = REGISTRY.register("fredbear_showtime", () -> new FredbearShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_HEAD = REGISTRY.register("unwithered_golden_freddy_head", () -> new UnwitheredGoldenFreddyHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_TORSO = REGISTRY.register("unwithered_golden_freddy_torso", () -> new UnwitheredGoldenFreddyTorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_RIGHT_ARM = REGISTRY.register("unwithered_golden_freddy_right_arm", () -> new UnwitheredGoldenFreddyRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_LEFT_ARM = REGISTRY.register("unwithered_golden_freddy_left_arm", () -> new UnwitheredGoldenFreddyLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_RIGHT_LEG = REGISTRY.register("unwithered_golden_freddy_right_leg", () -> new UnwitheredGoldenFreddyRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_LEFT_LEG = REGISTRY.register("unwithered_golden_freddy_left_leg", () -> new UnwitheredGoldenFreddyLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_SHOWTIME = REGISTRY.register("unwithered_golden_freddy_showtime", () -> new UnwitheredGoldenFreddyShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_HEAD = REGISTRY.register("unwithered_golden_bonnie_head", () -> new UnwitheredGoldenBonnieHeadBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_TORSO = REGISTRY.register("unwithered_golden_bonnie_torso", () -> new UnwitheredGoldenBonnieTorsoBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_RIGHT_ARM = REGISTRY.register("unwithered_golden_bonnie_right_arm", () -> new UnwitheredGoldenBonnieRightArmBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_LEFT_ARM = REGISTRY.register("unwithered_golden_bonnie_left_arm", () -> new UnwitheredGoldenBonnieLeftArmBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_RIGHT_LEG = REGISTRY.register("unwithered_golden_bonnie_right_leg", () -> new UnwitheredGoldenBonnieRightLegBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_LEFT_LEG = REGISTRY.register("unwithered_golden_bonnie_left_leg", () -> new UnwitheredGoldenBonnieLeftLegBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_SHOWTIME = REGISTRY.register("unwithered_golden_bonnie_showtime", () -> new UnwitheredGoldenBonnieShowtimeBlock());
	public static final RegistryObject<Block> DINER_FOXY_HEAD = REGISTRY.register("diner_foxy_head", () -> new DinerFoxyHeadBlock());
	public static final RegistryObject<Block> DINER_FOXY_TORSO = REGISTRY.register("diner_foxy_torso", () -> new DinerFoxyTorsoBlock());
	public static final RegistryObject<Block> DINER_FOXY_RIGHT_ARM = REGISTRY.register("diner_foxy_right_arm", () -> new DinerFoxyRightArmBlock());
	public static final RegistryObject<Block> DINER_FOXY_LEFT_ARM = REGISTRY.register("diner_foxy_left_arm", () -> new DinerFoxyLeftArmBlock());
	public static final RegistryObject<Block> DINER_FOXY_RIGHT_LEG = REGISTRY.register("diner_foxy_right_leg", () -> new DinerFoxyRightLegBlock());
	public static final RegistryObject<Block> DINER_FOXY_LEFT_LEG = REGISTRY.register("diner_foxy_left_leg", () -> new DinerFoxyLeftLegBlock());
	public static final RegistryObject<Block> DINER_FOXY_SHOWTIME = REGISTRY.register("diner_foxy_showtime", () -> new DinerFoxyShowtimeBlock());
	public static final RegistryObject<Block> DINER_FREDDY_HEAD = REGISTRY.register("diner_freddy_head", () -> new DinerFreddyHeadBlock());
	public static final RegistryObject<Block> DINER_FREDDY_TORSO = REGISTRY.register("diner_freddy_torso", () -> new DinerFreddyTorsoBlock());
	public static final RegistryObject<Block> DINER_FREDDY_RIGHT_ARM = REGISTRY.register("diner_freddy_right_arm", () -> new DinerFreddyRightArmBlock());
	public static final RegistryObject<Block> DINER_FREDDY_LEFT_ARM = REGISTRY.register("diner_freddy_left_arm", () -> new DinerFreddyLeftArmBlock());
	public static final RegistryObject<Block> DINER_FREDDY_RIGHT_LEG = REGISTRY.register("diner_freddy_right_leg", () -> new DinerFreddyRightLegBlock());
	public static final RegistryObject<Block> DINER_FREDDY_LEFT_LEG = REGISTRY.register("diner_freddy_left_leg", () -> new DinerFreddyLeftLegBlock());
	public static final RegistryObject<Block> DINER_FREDDY_SHOWTIME = REGISTRY.register("diner_freddy_showtime", () -> new DinerFreddyShowtimeBlock());
	public static final RegistryObject<Block> DINER_BONNIE_HEAD = REGISTRY.register("diner_bonnie_head", () -> new DinerBonnieHeadBlock());
	public static final RegistryObject<Block> DINER_BONNIE_TORSO = REGISTRY.register("diner_bonnie_torso", () -> new DinerBonnieTorsoBlock());
	public static final RegistryObject<Block> DINER_BONNIE_RIGHT_ARM = REGISTRY.register("diner_bonnie_right_arm", () -> new DinerBonnieRightArmBlock());
	public static final RegistryObject<Block> DINER_BONNIE_LEFT_ARM = REGISTRY.register("diner_bonnie_left_arm", () -> new DinerBonnieLeftArmBlock());
	public static final RegistryObject<Block> DINER_BONNIE_RIGHT_LEG = REGISTRY.register("diner_bonnie_right_leg", () -> new DinerBonnieRightLegBlock());
	public static final RegistryObject<Block> DINER_BONNIE_LEFT_LEG = REGISTRY.register("diner_bonnie_left_leg", () -> new DinerBonnieLeftLegBlock());
	public static final RegistryObject<Block> DINER_BONNIE_SHOWTIME = REGISTRY.register("diner_bonnie_showtime", () -> new DinerBonnieShowtimeBlock());
	public static final RegistryObject<Block> DINER_CHICA_HEAD = REGISTRY.register("diner_chica_head", () -> new DinerChicaHeadBlock());
	public static final RegistryObject<Block> DINER_CHICA_TORSO = REGISTRY.register("diner_chica_torso", () -> new DinerChicaTorsoBlock());
	public static final RegistryObject<Block> DINER_CHICA_RIGHT_ARM = REGISTRY.register("diner_chica_right_arm", () -> new DinerChicaRightArmBlock());
	public static final RegistryObject<Block> DINER_CHICA_LEFT_ARM = REGISTRY.register("diner_chica_left_arm", () -> new DinerChicaLeftArmBlock());
	public static final RegistryObject<Block> DINER_CHICA_RIGHT_LEG = REGISTRY.register("diner_chica_right_leg", () -> new DinerChicaRightLegBlock());
	public static final RegistryObject<Block> DINER_CHICA_LEFT_LEG = REGISTRY.register("diner_chica_left_leg", () -> new DinerChicaLeftLegBlock());
	public static final RegistryObject<Block> DINER_CHICA_SHOWTIME = REGISTRY.register("diner_chica_showtime", () -> new DinerChicaShowtimeBlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_BONNIE_SHOWTIME_A = REGISTRY.register("unwithered_golden_bonnie_showtime_a", () -> new UnwitheredGoldenBonnieShowtimeABlock());
	public static final RegistryObject<Block> UNWITHERED_FOXY_SHOWTIME_A = REGISTRY.register("unwithered_foxy_showtime_a", () -> new UnwitheredFoxyShowtimeABlock());
	public static final RegistryObject<Block> UNWITHERED_FREDDY_SHOWTIME_A = REGISTRY.register("unwithered_freddy_showtime_a", () -> new UnwitheredFreddyShowtimeABlock());
	public static final RegistryObject<Block> UNWITHERED_BONNIE_SHOWTIME_A = REGISTRY.register("unwithered_bonnie_showtime_a", () -> new UnwitheredBonnieShowtimeABlock());
	public static final RegistryObject<Block> UNWITHERED_CHICA_SHOWTIME_A = REGISTRY.register("unwithered_chica_showtime_a", () -> new UnwitheredChicaShowtimeABlock());
	public static final RegistryObject<Block> UNWITHERED_GOLDEN_FREDDY_SHOWTIME_A = REGISTRY.register("unwithered_golden_freddy_showtime_a", () -> new UnwitheredGoldenFreddyShowtimeABlock());
	public static final RegistryObject<Block> FRED_BEAR_SHOWTIME_A = REGISTRY.register("fred_bear_showtime_a", () -> new FredBearShowtimeABlock());
	public static final RegistryObject<Block> SPRING_BONNIE_SHOWTIME_A = REGISTRY.register("spring_bonnie_showtime_a", () -> new SpringBonnieShowtimeABlock());
	public static final RegistryObject<Block> DINER_FOXY_SHOWTIME_A = REGISTRY.register("diner_foxy_showtime_a", () -> new DinerFoxyShowtimeABlock());
	public static final RegistryObject<Block> DINER_FREDDY_SHOWTIME_A = REGISTRY.register("diner_freddy_showtime_a", () -> new DinerFreddyShowtimeABlock());
	public static final RegistryObject<Block> DINER_BONNIE_SHOWTIME_A = REGISTRY.register("diner_bonnie_showtime_a", () -> new DinerBonnieShowtimeABlock());
	public static final RegistryObject<Block> DINER_CHICA_SHOWTIME_A = REGISTRY.register("diner_chica_showtime_a", () -> new DinerChicaShowtimeABlock());
}
